### ISSUE TITLE
Error importing on vue 3

### ISSUE THREAD

**Issue by titogarrido** [M-Media-Group/Vue3-Meta-Tags#3]
I just installed it using 

`npm i @m-media/vue3-meta-tags --save`

and imported on my `main.js`

`import { metaTagPlugin } from "@m-media/vue3-meta-tags";`

This is the error on console:

[vite] Internal server error: Failed to resolve entry for package "@m-media/vue3-meta-tags". The package may have incorrect main/module/exports specified in its package.json.

**Comment by titogarrido** [comment]
#2 resolves this issue.

**Comment by mwargan** [comment]
@titogarrido thanks for the investigation! I've merged it, will need to publish an update on NPM soon.

**Comment by mwargan** [comment]
@titogarrido resolved with version 0.0.5. Thank you for the report!
